// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xspptyrfxvfkrnxvednt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzcHB0eXJmeHZma3JueHZlZG50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3ODI4MzgsImV4cCI6MjA2MTM1ODgzOH0.zEuN6ZToSbuH0XIrKmlJoGXZIqbXrz0hZuGU7dZ4Tbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);